#!/bin/bash  

if [ $# -ne 2 ]; then  
    echo "You need a Host-IP and Target-IP"  
    echo "Example: mxhelp hostip targetip"  
    exit 1  
fi  
 
IP=$1 
TGT=$2 
echo "" 
echo "Mike is Helping..."
ipold=$(cat ~/mxhelp/z_myip)
tgtold=$(cat ~/mxhelp/z_tgt)

echo 'UPDATE IP :' $ipold '-->' $IP  
echo 'UPDATE TGT:' $tgtold '-->' $TGT  
  
if   [[ ! $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then 
    echo "IP not valid." 
    exit 1 
elif [[ ! $TGT =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then 
    echo "Target IP not valid." 
    exit 1 
elif [[ $IP = $TGT ]]; then 
    echo "IP and TGT are the same. Abort - You will wreak havoc." 
    exit 1 
elif [[ $IP = $tgtold ]]; then 
    echo "IP and OLDTGT are the same. Abort - You will wreak havoc." 
    exit 1 
elif [[ $TGT = $ipold ]]; then 
    echo "TGT and OLDIP are the same. Abort - You will wreak havoc." 
    exit 1 
fi 
 
#Search and fix 
find ~/mxhelp/mx* -type f -exec sed -i 's/'"$ipold"'/'"$IP"'/gI' {} \;
find ~/mxhelp/mx* -type f -exec sed -i 's/'"$tgtold"'/'"$TGT"'/gI' {} \;

#Update to capture latest
echo $IP > ~/mxhelp/z_myip
echo $TGT > ~/mxhelp/z_tgt

echo "-------------------------------------" 
echo "Initial nmap" 
echo -e "\e[1;35m" 
echo "sudo nmap -p- --min-rate=1000 -T4 -v" $TGT "-Pn | tee nmap-ports" 
echo "ports=\$(grep ^[0-9] ./nmap-ports | cut -d '/' -f 1 | tr '\n' ',' | sed s/,$//)" 
echo "echo -e '\nPorts-to-Scan:'" $ports
echo "sudo nmap -sV -sC -v -p \$ports" $TGT "-Pn | tee nmap-fulltcp"
echo "echo -e '\nSummary:'"
echo "grep ^[0-9] ./nmap-fulltcp" 
echo -e "\e[1;m" 

echo "-------------------------------------" 
echo "Consider UDP" 
echo -e "\e[1;35m" 
echo "sudo nmap --top-ports 20 -sU -sV -sC -v" $TGT "| tee nmap-udp20" 
echo "sudo nmap -p- -Pn –sU --min-rate 10000 -v" $TGT "| tee nmap-udp" 
echo -e "\e[1;m" 

echo "-------------------------------------" 
echo "Consider nmapAutomator"
echo "sudo nmapAutomator.sh -H" $TGT "-t Script | tee nmap-auto-script
echo "sudo nmapAutomator.sh -H" $TGT "-t Vulns | tee nmap-auto-vulns
echo "sudo nmapAutomator.sh -H" $TGT "-t Recon | tee nmap-auto-recon
echo "sudo nmapAutomator.sh -H" $TGT "-t All | tee nmap-auto-all

echo "-------------------------------------" 
echo "More" 
ls ~/mxhelp/
echo ""
