#!/bin/bash  

if [ $# -ne 2 ]; then  
    echo "You need a Host-IP and Target-IP"  
    echo "Example: mxhelp hostip targetip"  
    exit 1  
fi  
 
IP=$1 
TGT=$2 
echo "" 
echo "Mike is Helping..."
ipold=$(cat ~/mxhelp/ipoldme)
tgtold=$(cat ~/mxhelp/ipoldtgt)

echo 'UPDATE IP :' $ipold '-->' $IP  
echo 'UPDATE TGT:' $tgtold '-->' $TGT  
  
if   [[ ! $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then 
    echo "IP not valid." 
    exit 1 
elif [[ ! $TGT =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then 
    echo "Target IP not valid." 
    exit 1 
elif [[ $IP = $TGT ]]; then 
    echo "IP and TGT are the same. Abort - You will wreak havoc." 
    exit 1 
elif [[ $IP = $tgtold ]]; then 
    echo "IP and OLDTGT are the same. Abort - You will wreak havoc." 
    exit 1 
elif [[ $TGT = $ipold ]]; then 
    echo "TGT and OLDIP are the same. Abort - You will wreak havoc." 
    exit 1 
fi 
 
#Search and fix 
find ~/mxhelp/mx* -type f -exec sed -i 's/'"$ipold"'/'"$IP"'/gI' {} \;
find ~/mxhelp/mx* -type f -exec sed -i 's/'"$tgtold"'/'"$TGT"'/gI' {} \;

#Update to capture latest
echo $IP > ~/mxhelp/ipoldme
echo $TGT > ~/mxhelp/ipoldtgt

echo "-------------------------------------" 
echo "Initial nmap" 
echo -e "\e[1;35m" 
echo "nmap -p- --min-rate=1000 -T4" $TGT "-Pn | tee ports.nmap" 
echo "grep ^[0-9] ./ports.nmap" 
echo "ports=\$(grep ^[0-9] ./ports.nmap | cut -d '/' -f 1 | tr '\n' ',' | sed s/,$//)" 
echo "nmap -A -p \$ports" $TGT "-Pn -oA nmaptcp" 
echo "grep ^[0-9] ./nmaptcp.nmap" 
echo -e "\e[1;m" 
 
echo "-------------------------------------" 
echo "Consider UDP" 
echo -e "\e[1;35m" 
echo "nmap --top-ports 20 -sU -sV -sC" $TGT "-oG nmapudp20" 
echo "nmap -p0-65535 -Pn –sU" $TGT "-oG nmapudp" 
echo -e "\e[1;m" 

echo "-------------------------------------" 
echo "Consider nmapAutomator" 
echo -e "\e[1;35m" 
echo "nmapAutomator.sh -H" $TGT "-t Script | tee script.na" 
echo "nmapAutomator.sh -H" $TGT "-t Vulns | tee vulns.na" 
echo "nmapAutomator.sh -H" $TGT "-t Recon | tee recon.na" 
echo -e "\e[1;m" 

echo "-------------------------------------" 
ls ~/mxhelp/mx*
echo ""
